language: generic 
sudo: required
services:
  -docker


before_install:
  - docker build -t nabeegacryptocode/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nabeegacryptocode/docker-react npm run test












